###
GET http://localhost:8080/book

###
GET http://localhost:8080/book?sellerId=69b812d44b853f46dd6910e5

###
GET http://localhost:8080/book/69b813b5bd32ffb6e1c07b6c

###
POST http://localhost:8080/book
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWI4MTJkNDRiODUzZjQ2ZGQ2OTEwZTUiLCJpYXQiOjE3NzUxMzYzMTYsImV4cCI6MTc3NTEzOTkxNn0.KuL8nStkfT0bGN-7SewfUKKKTEL05OP_WOV7r1ZPF2M
Content-Type: application/json

{
    "sellerId": "69b812d44b853f46dd6910e5",
    "imageUrl": "image3.jpg",
    "title": "Harry Potter and the Sorcerer's Stone",
    "author":"J.K. Rowling",
    "price": "15.2",
    "summery":"book 1 summery",
    "description": "book 1 description",
    "date": "2026-01-01T13:31:41.786Z"
}

###
PUT http://localhost:8080/book/69b813b5bd32ffb6e1c07b6c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWI4MTJkNDRiODUzZjQ2ZGQ2OTEwZTUiLCJpYXQiOjE3NzM2NzExMjQsImV4cCI6MTc3MzY3NDcyNH0.Pg0rh77LzjQ5dBQirkM_4JRIk5V8v98WRe2fKvyWtXY
Content-Type: application/json

{
    "imageUrl": "newimage1.jpg",
    "description": "new desc",
    "date": "2026-01-01T13:31:41.786Z"
}

###
DELETE  http://localhost:8080/book/69b813b5bd32ffb6e1c07b6c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWI4MTJkNDRiODUzZjQ2ZGQ2OTEwZTUiLCJpYXQiOjE3NzM2NzExMjQsImV4cCI6MTc3MzY3NDcyNH0.Pg0rh77LzjQ5dBQirkM_4JRIk5V8v98WRe2fKvyWtXY

###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "username": "ee",
    "email": "emaa@gmail.com",
    "password": "12344"
}

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "emaa@gmail.com",
    "password": "12344"
}

###
POST http://localhost:8080/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": 
        "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWI4MTJkNDRiODUzZjQ2ZGQ2OTEwZTUiLCJpYXQiOjE3NzUxMzQ2MDksImV4cCI6MTc3NTIyMTAwOX0.V2eQLedtT5pwg8sQb7PdDWDjfb70-Y0_ng3iemamkhI"
}

###
POST http://localhost:8080/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTdhNTQ4YjU1NGMyODI4NTUyMDFkNjciLCJpYXQiOjE3Njk2MzA2OTAsImV4cCI6MTc2OTcxNzA5MH0.xx8jaslLMRUostRbrU48CITe18u5Exp8Zy9NRVe3vhw
Content-Type: application/json
